name: HtmlTable.Paginate
author: [Oran Leiba, etootim.com]
category: [Interface, Utilities]
tags: [HtmlTable, Pagination, Scroll]
#docs: http://url.to.docs
demo: http://www.etootim.com/hub/HtmlTable.Paginate.Demo/HtmlTable.Paginate.html
current: 1.0