name: HtmlTable.Paginate
author: oranleiba
category: Interface
tags: [HtmlTable, Pagination, Scroll]
#docs: http://url.to.docs
demo: http://www.etootim.com/hub/HtmlTable.Paginate.Demo/HtmlTable.Paginate.html
current: 1